"""
Agent responsible for providing educational calligraphy advice, critique, and progress paths.

This MentorAgent acts as a virtual calligraphy instructor, using Gemini via GeminiClient 
to generate custom exercises, style tips, progress reports, and personalized training plans.
"""

import json
import logging
from typing import Dict, Any, List
from gemini_client import GeminiClient

# Set up module-specific logger
logger = logging.getLogger(__name__)

# Base system instructions for educational mentoring
SYSTEM_INSTRUCTION = (
    "You are an expert virtual calligraphy instructor and mentor for Calligraphy Central.\n"
    "Your goal is to provide supportive, highly educational, clear, and inspiring guidance to calligraphy students.\n"
    "Respond only in structured JSON matching the requested schemas to ensure compatibility."
)

class MentorAgent:
    """
    MentorAgent acts as a virtual calligraphy instructor.
    
    It analyzes requests to provide customized training exercises, style critiques,
    and learning roadmaps using the Gemini API.
    
    Future Extensibility plans:
    - Visual Art Critique: Accept images of user practice sheets to analyze lines,
      slant deviation, grid alignment, and ink consistency.
    - Long-Term Learning Memory: Save student history to dynamically adjust difficulty
      and track improvements across submissions.
    - Tool Calling / Course Registration: Interface with course catalogs to suggest
      specific live workshops or community study sessions matching the student's weaknesses.
    """

    def __init__(self) -> None:
        """
        Initialize the MentorAgent.
        Instantiates a GeminiClient for sending educational prompt requests.
        """
        logger.info("Initializing MentorAgent...")
        try:
            self.gemini_client = GeminiClient()
            logger.info("GeminiClient successfully initialized in MentorAgent.")
        except Exception as e:
            logger.error(f"Failed to initialize GeminiClient within MentorAgent: {e}", exc_info=True)
            self.gemini_client = None

    def _parse_gemini_json(self, response_text: str, default_val: Any) -> Any:
        """
        Cleans markdown code fences and safely parses JSON responses.

        Args:
            response_text (str): The raw string generated by Gemini.
            default_val (Any): The fallback default value if parsing fails.

        Returns:
            Any: The parsed JSON object or default_val.
        """
        try:
            cleaned = response_text.strip()
            # Remove Markdown JSON block wrappers
            if cleaned.startswith("```json"):
                cleaned = cleaned[7:]
            elif cleaned.startswith("```"):
                cleaned = cleaned[3:]
            if cleaned.endswith("```"):
                cleaned = cleaned[:-3]
            cleaned = cleaned.strip()
            
            return json.loads(cleaned)
        except Exception as e:
            logger.warning(f"Failed to parse JSON response from Gemini: {e}. Raw response: {response_text}")
            return default_val

    def get_beginner_tips(self) -> List[str]:
        """
        Retrieves foundational tips for beginner calligraphers.

        Returns:
            List[str]: Actionable beginner practice tips.
        """
        default_fallback = [
            "Maintain a consistent 45-degree pen angle.",
            "Practice your basic strokes before forming letters.",
            "Keep your posture straight and your arm relaxed."
        ]
        if not self.gemini_client:
            return default_fallback

        try:
            prompt = (
                "Generate a list of 3 actionable, foundational, and inspiring tips for a beginner calligrapher. "
                "Respond ONLY with a JSON array of strings containing the tips."
            )
            full_prompt = f"{SYSTEM_INSTRUCTION}\n\nTask:\n{prompt}"
            response = self.gemini_client.generate_response(full_prompt)
            return self._parse_gemini_json(response, default_fallback)
        except Exception as e:
            logger.error(f"Error in get_beginner_tips: {e}", exc_info=True)
            return default_fallback

    def get_style_guidance(self, style: str) -> Dict[str, Any]:
        """
        Provides specific tips and historical context for a requested calligraphy style.

        Args:
            style (str): The calligraphy script style (e.g. Copperplate, Gothic).

        Returns:
            Dict[str, Any]: A dictionary containing style name and guidance description.
        """
        default_fallback = {
            "style": style,
            "guidance": f"Focus on the characteristic swells and hairline strokes typical of {style}."
        }
        if not self.gemini_client:
            return default_fallback

        try:
            prompt = (
                f"Provide expert tips, style guides, and brief historical context for the style: '{style}'. "
                "Highlight key parameters like pen angle, slant, and nib choice. "
                "Respond ONLY with a JSON object in this format:\n"
                "{\n"
                "  \"style\": \"StatedStyleName\",\n"
                "  \"guidance\": \"Nuanced educational guidelines and tips.\"\n"
                "}"
            )
            full_prompt = f"{SYSTEM_INSTRUCTION}\n\nTask:\n{prompt}"
            response = self.gemini_client.generate_response(full_prompt)
            return self._parse_gemini_json(response, default_fallback)
        except Exception as e:
            logger.error(f"Error in get_style_guidance: {e}", exc_info=True)
            return default_fallback

    def suggest_practice_exercises(self, level: str) -> List[Dict[str, Any]]:
        """
        Recommends drills and exercises appropriate for the user's skill level.

        Args:
            level (str): The current skill tier of the user (e.g. Beginner, Intermediate).

        Returns:
            List[Dict[str, Any]]: Suggested drills with repetition counts and focus areas.
        """
        default_fallback = [
            {"exercise": "Ovals and Loops", "reps": 20, "level": level},
            {"exercise": "Connecting Ascenders", "reps": 15, "level": level}
        ]
        if not self.gemini_client:
            return default_fallback

        try:
            prompt = (
                f"Create 3 structured and beneficial calligraphy practice drills for the skill level: '{level}'. "
                "Specify the exercise name, number of repetitions, and goal of the drill. "
                "Respond ONLY with a JSON array of objects, where each object has these exact keys:\n"
                "  \"exercise\": \"Name of drill\",\n"
                "  \"reps\": [integer],\n"
                "  \"level\": \"LevelName\"\n"
            )
            full_prompt = f"{SYSTEM_INSTRUCTION}\n\nTask:\n{prompt}"
            response = self.gemini_client.generate_response(full_prompt)
            return self._parse_gemini_json(response, default_fallback)
        except Exception as e:
            logger.error(f"Error in suggest_practice_exercises: {e}", exc_info=True)
            return default_fallback

    def review_progress(self, user_id: Any) -> Dict[str, Any]:
        """
        Analyzes a user's progress and provides automated growth feedback.

        Args:
            user_id: The identifier of the calligrapher.

        Returns:
            Dict[str, Any]: User progress critique.
        """
        default_fallback = {
            "user_id": user_id,
            "feedback": "Your spacing has improved significantly over your recent practice uploads."
        }
        if not self.gemini_client:
            return default_fallback

        try:
            prompt = (
                f"Generate a progress review critique for calligraphy student ID '{user_id}'. "
                "Be encouraging, highlight progress in stroke control and spacing, and point out one developmental focus. "
                "Respond ONLY with a JSON object in this format:\n"
                "{\n"
                "  \"user_id\": [input user_id],\n"
                "  \"feedback\": \"Encouraging progress feedback and critique review.\"\n"
                "}"
            )
            full_prompt = f"{SYSTEM_INSTRUCTION}\n\nTask:\n{prompt}"
            response = self.gemini_client.generate_response(full_prompt)
            return self._parse_gemini_json(response, default_fallback)
        except Exception as e:
            logger.error(f"Error in review_progress: {e}", exc_info=True)
            return default_fallback

    def recommend_learning_path(self, user_id: Any) -> Dict[str, Any]:
        """
        Generates a structured syllabus or learning milestones roadmap for the student.

        Args:
            user_id: The identifier of the calligrapher.

        Returns:
            Dict[str, Any]: A step-by-step roadmap list.
        """
        default_fallback = {
            "user_id": user_id,
            "path": [
                "Master basic strokes",
                "Learn lowercase alphabet",
                "Learn uppercase alphabet",
                "Word connections"
            ]
        }
        if not self.gemini_client:
            return default_fallback

        try:
            prompt = (
                f"Create a 4-step progressive learning syllabus roadmap for calligrapher ID '{user_id}'. "
                "Focus on moving from basic techniques to style-specific layout designs. "
                "Respond ONLY with a JSON object in this format:\n"
                "{\n"
                "  \"user_id\": [input user_id],\n"
                "  \"path\": [\"Step 1 description\", \"Step 2 description\", \"Step 3 description\", \"Step 4 description\"]\n"
                "}"
            )
            full_prompt = f"{SYSTEM_INSTRUCTION}\n\nTask:\n{prompt}"
            response = self.gemini_client.generate_response(full_prompt)
            return self._parse_gemini_json(response, default_fallback)
        except Exception as e:
            logger.error(f"Error in recommend_learning_path: {e}", exc_info=True)
            return default_fallback

    def mentor_response(self, request_type: str = "tips", filters: Dict[str, Any] = None) -> Dict[str, Any]:
        """
        Main orchestration method for the MentorAgent.
        
        Routes the mentoring request to the corresponding strategy based on request_type
        and aggregates the resulting advice response.

        Args:
            request_type (str): Type of mentoring advice (guidance, exercises, review, path, tips).
            filters (Dict[str, Any]): Parameters detailing context (e.g. style name, user level, user_id).

        Returns:
            Dict[str, Any]: Structured dictionary wrapping the generated critique/advice.
        """
        try:
            logger.info(f"Orchestrating mentoring advice for type: {request_type}")
            advice = None
            
            if filters is None:
                filters = {}

            # Route to the appropriate mentoring strategy
            if request_type == "guidance" and "style" in filters:
                advice = self.get_style_guidance(filters["style"])
            elif request_type == "exercises" and "level" in filters:
                advice = self.suggest_practice_exercises(filters["level"])
            elif request_type == "review" and "user_id" in filters:
                advice = self.review_progress(filters["user_id"])
            elif request_type == "path" and "user_id" in filters:
                advice = self.recommend_learning_path(filters["user_id"])
            else:
                # Default to beginner tips
                advice = self.get_beginner_tips()

            return {
                "request_type": request_type,
                "advice": advice,
                "status": "success"
            }
            
        except Exception as e:
            logger.error(f"Error in mentor_response orchestration: {e}", exc_info=True)
            return {
                "request_type": "error",
                "advice": "An error occurred while generating mentoring advice.",
                "status": "failed"
            }
