"""
Agent responsible for analyzing user preferences and generating calligraphy recommendations.

This RecommendationAgent utilizes Gemini via GeminiClient to suggest style inspiration,
relevant tags, similar works, trending pieces, and personalized practice suggestions.
"""

import json
import logging
from typing import Dict, Any, List
from gemini_client import GeminiClient

# Set up module-specific logger
logger = logging.getLogger(__name__)

# Base system instructions for recommendation curation
SYSTEM_INSTRUCTION = (
    "You are an expert calligraphy curator and recommendation specialist for Calligraphy Central. "
    "Your objective is to provide educational, inspiring, personalized, concise, and context-aware recommendations. "
    "Where appropriate, ensure recommendations are beginner-friendly and explain calligraphic concepts clearly."
)

class RecommendationAgent:
    """
    RecommendationAgent provides personalized and content-based recommendations.
    
    It analyzes styles, tags, similarity to other posts, and trending metrics, 
    generating structured recommendations using Gemini.
    
    Future Extensibility plans:
    - Vision-based Recommendations: Process uploaded images to recommend similar works
      by analyzing brushwork, nib style, and execution patterns.
    - Collaborative Filtering Memory: Maintain context of historically viewed posts to refine recommendations.
    - Tool Calling / Semantic Routing: Intercept recommendation requests to retrieve candidate lists
      from the application database before feeding them to Gemini for prioritization.
    """

    def __init__(self) -> None:
        """
        Initialize the RecommendationAgent.
        Instantiates a GeminiClient for processing recommendation requests.
        """
        logger.info("Initializing RecommendationAgent...")
        try:
            self.gemini_client = GeminiClient()
            logger.info("GeminiClient successfully initialized in RecommendationAgent.")
        except Exception as e:
            logger.error(f"Failed to initialize GeminiClient within RecommendationAgent: {e}", exc_info=True)
            self.gemini_client = None

    def _parse_gemini_json(self, response_text: str, default_val: Any) -> Any:
        """
        Removes markdown code fences and safely parses JSON responses.

        Args:
            response_text (str): The raw string generated by Gemini.
            default_val (Any): The fallback default value if parsing fails.

        Returns:
            Any: The parsed JSON object or default_val.
        """
        try:
            cleaned = response_text.strip()
            # Remove Markdown JSON block wrappers
            if cleaned.startswith("```json"):
                cleaned = cleaned[7:]
            elif cleaned.startswith("```"):
                cleaned = cleaned[3:]
            if cleaned.endswith("```"):
                cleaned = cleaned[:-3]
            cleaned = cleaned.strip()
            
            return json.loads(cleaned)
        except Exception as e:
            logger.warning(f"Failed to parse JSON response from Gemini: {e}. Raw response: {response_text}")
            return default_val

    def recommend_by_style(self, style: str) -> List[Dict[str, Any]]:
        """
        Recommends posts that match a specific calligraphy style.

        Args:
            style (str): The calligraphy script style (e.g. Copperplate, Gothic).

        Returns:
            List[Dict[str, Any]]: A list of recommended posts matching the style.
        """
        default_fallback = [{"id": 101, "style": style, "reason": "Style match fallback."}]
        if not self.gemini_client:
            logger.error("GeminiClient is not available. recommend_by_style returning fallback.")
            return default_fallback

        try:
            prompt = (
                f"Generate a list of 3 recommended calligraphy post items for the style: '{style}'. "
                "Make each recommendation highly educational and inspiring. Explain stroke rules or historical notes. "
                "Respond ONLY with a JSON array of objects, where each object has these exact keys:\n"
                "  \"id\": [integer, e.g. 101, 102, ...],\n"
                "  \"style\": [string matching the style requested],\n"
                "  \"reason\": [detailed, concise, calligraphy-focused educational reason]\n"
            )
            full_prompt = f"{SYSTEM_INSTRUCTION}\n\nTask:\n{prompt}"
            response = self.gemini_client.generate_response(full_prompt)
            return self._parse_gemini_json(response, default_fallback)
        except Exception as e:
            logger.error(f"Error in recommend_by_style: {e}", exc_info=True)
            return default_fallback

    def recommend_by_tags(self, tags: Any) -> List[Dict[str, Any]]:
        """
        Recommends posts based on a list of preferred tags.

        Args:
            tags: Tag criteria (e.g., list of tags, string).

        Returns:
            List[Dict[str, Any]]: Suggested posts.
        """
        default_fallback = [{"id": 102, "tags": str(tags), "reason": "Tag match fallback."}]
        if not self.gemini_client:
            logger.error("GeminiClient is not available. recommend_by_tags returning fallback.")
            return default_fallback

        try:
            prompt = (
                f"Generate a list of 3 recommended calligraphy post items matching the tags/topics: '{tags}'. "
                "Ensure the recommendations are beginner-friendly and explain how they relate to the tags. "
                "Respond ONLY with a JSON array of objects, where each object has these exact keys:\n"
                "  \"id\": [integer],\n"
                "  \"tags\": [string representation of tags],\n"
                "  \"reason\": [concise, educational and inspiring reasoning for the tag match]\n"
            )
            full_prompt = f"{SYSTEM_INSTRUCTION}\n\nTask:\n{prompt}"
            response = self.gemini_client.generate_response(full_prompt)
            return self._parse_gemini_json(response, default_fallback)
        except Exception as e:
            logger.error(f"Error in recommend_by_tags: {e}", exc_info=True)
            return default_fallback

    def recommend_similar_posts(self, post_id: Any) -> List[Dict[str, Any]]:
        """
        Recommends posts that are visually or semantically similar to a given post.

        Args:
            post_id: The baseline post identifier.

        Returns:
            List[Dict[str, Any]]: Similar post recommendation metadata.
        """
        default_fallback = [{"id": 103, "similar_to": post_id, "reason": "Content similarity fallback."}]
        if not self.gemini_client:
            logger.error("GeminiClient is not available. recommend_similar_posts returning fallback.")
            return default_fallback

        try:
            prompt = (
                f"Generate a list of 3 recommended calligraphy post items that are semantically or visually similar "
                f"to post ID '{post_id}'. Explain why they are similar in a technical, inspiring way (layout, spacing, weight). "
                "Respond ONLY with a JSON array of objects, where each object has these exact keys:\n"
                "  \"id\": [integer],\n"
                "  \"similar_to\": [post_id matching input],\n"
                "  \"reason\": [inspiring explanation comparing layout, stroke quality, or execution]\n"
            )
            full_prompt = f"{SYSTEM_INSTRUCTION}\n\nTask:\n{prompt}"
            response = self.gemini_client.generate_response(full_prompt)
            return self._parse_gemini_json(response, default_fallback)
        except Exception as e:
            logger.error(f"Error in recommend_similar_posts: {e}", exc_info=True)
            return default_fallback

    def recommend_trending(self) -> List[Dict[str, Any]]:
        """
        Recommends posts that are currently trending based on platform metrics.

        Returns:
            List[Dict[str, Any]]: Trending post items.
        """
        default_fallback = [{"id": 104, "trend_score": 99, "reason": "Trending fallback."}]
        if not self.gemini_client:
            logger.error("GeminiClient is not available. recommend_trending returning fallback.")
            return default_fallback

        try:
            prompt = (
                "Generate a list of 3 trending calligraphy post items currently popular in the community. "
                "Assess their visual or technical popularity and explain what other scribes can learn from them. "
                "Respond ONLY with a JSON array of objects, where each object has these exact keys:\n"
                "  \"id\": [integer],\n"
                "  \"trend_score\": [integer between 90 and 100],\n"
                "  \"reason\": [explanation of why this piece is popular and what calligraphers can learn from it]\n"
            )
            full_prompt = f"{SYSTEM_INSTRUCTION}\n\nTask:\n{prompt}"
            response = self.gemini_client.generate_response(full_prompt)
            return self._parse_gemini_json(response, default_fallback)
        except Exception as e:
            logger.error(f"Error in recommend_trending: {e}", exc_info=True)
            return default_fallback

    def recommend_for_user(self, user_id: Any) -> List[Dict[str, Any]]:
        """
        Provides personalized recommendations based on a user's ID.

        Args:
            user_id: The recipient user identifier.

        Returns:
            List[Dict[str, Any]]: Custom recommendations.
        """
        default_fallback = [{"id": 105, "user_id": user_id, "reason": "Personalized preference fallback."}]
        if not self.gemini_client:
            logger.error("GeminiClient is not available. recommend_for_user returning fallback.")
            return default_fallback

        try:
            prompt = (
                f"Provide 3 personalized calligraphy recommendations for user ID '{user_id}' based on their "
                "hypothetical progression path (from foundational strokes to advanced layout and composition). "
                "Explain how each recommended drill/style benefits their learning stage. "
                "Respond ONLY with a JSON array of objects, where each object has these exact keys:\n"
                "  \"id\": [integer],\n"
                "  \"user_id\": [user_id matching input],\n"
                "  \"reason\": [highly encouraging and customized suggestion, targeting specific practice drills]\n"
            )
            full_prompt = f"{SYSTEM_INSTRUCTION}\n\nTask:\n{prompt}"
            response = self.gemini_client.generate_response(full_prompt)
            return self._parse_gemini_json(response, default_fallback)
        except Exception as e:
            logger.error(f"Error in recommend_for_user: {e}", exc_info=True)
            return default_fallback

    def recommend_posts(self, recommendation_type: str = "trending", filters: Dict[str, Any] = None) -> Dict[str, Any]:
        """
        Main orchestration method for the RecommendationAgent.
        
        Routes the recommendation request to the appropriate specific method based on 
        recommendation_type, and formats the output response matching the expected schema.

        Args:
            recommendation_type (str): Type of suggestion (style, tags, similar, user, trending).
            filters (Dict[str, Any]): Search constraints (e.g. style name, tags list, post_id).

        Returns:
            Dict[str, Any]: A structured response including recommendations (also alias results),
                            type, and count.
        """
        try:
            logger.info(f"Orchestrating recommendations for type: {recommendation_type}")
            recommendations = []
            
            if filters is None:
                filters = {}

            # Route to the appropriate recommendation strategy
            if recommendation_type == "style" and "style" in filters:
                recommendations = self.recommend_by_style(filters["style"])
            elif recommendation_type == "tags" and "tags" in filters:
                recommendations = self.recommend_by_tags(filters["tags"])
            elif recommendation_type == "similar" and "post_id" in filters:
                recommendations = self.recommend_similar_posts(filters["post_id"])
            elif recommendation_type == "user" and "user_id" in filters:
                recommendations = self.recommend_for_user(filters["user_id"])
            else:
                # Default to trending
                recommendations = self.recommend_trending()

            # Construct the final response dictionary supporting both results and recommendations key
            response = {
                "recommendation_type": recommendation_type,
                "recommendations": recommendations,
                "results": recommendations,  # Backward compatibility alias
                "count": len(recommendations)
            }
            return response
            
        except Exception as e:
            logger.error(f"Error in recommend_posts orchestration: {e}", exc_info=True)
            # Return a graceful fallback dictionary
            return {
                "recommendation_type": recommendation_type,
                "recommendations": [],
                "results": [],
                "count": 0
            }
