"""
Agent responsible for providing semantic and keyword search capabilities across the calligraphy platform.

This SearchAgent parses user inputs, understands search intents, and simulates semantic matches 
by querying the Gemini API via GeminiClient.
"""

import json
import logging
from typing import Dict, Any, List
from gemini_client import GeminiClient

# Set up module-specific logger
logger = logging.getLogger(__name__)

# Base system instructions for calligraphic search interpretation
SYSTEM_INSTRUCTION = (
    "You are an expert calligraphy search specialist for Calligraphy Central.\n"
    "Your goal is to parse search queries, understand calligraphic user intents, and generate highly relevant search matches.\n"
    "Respond only in structured JSON matching the requested schemas to ensure compatibility."
)

class SearchAgent:
    """
    SearchAgent handles complex querying over calligraphy posts and user data.
    
    It supports structured filters (style, title, language, tags) and advanced
    contextual search queries using Gemini.
    
    Future Extensibility plans:
    - Vector Database Retrieval: Connect to databases such as Pinecone, Milvus, or ChromaDB
      using text embeddings to search across millions of vectorized posts.
    - Vision-based Search: Retrieve similar visual artworks by generating image embeddings
      and performing similarity search.
    - Query Expansion: Ask Gemini to expand shorthand scripts (e.g. 'spence' -> 'Spencerian')
      to improve database keyword matching.
    """

    def __init__(self) -> None:
        """
        Initialize the SearchAgent.
        Instantiates a GeminiClient for processing search requests.
        """
        logger.info("Initializing SearchAgent...")
        try:
            self.gemini_client = GeminiClient()
            logger.info("GeminiClient successfully initialized in SearchAgent.")
        except Exception as e:
            logger.error(f"Failed to initialize GeminiClient within SearchAgent: {e}", exc_info=True)
            self.gemini_client = None

    def _parse_gemini_json(self, response_text: str, default_val: Any) -> Any:
        """
        Removes markdown code fences and safely parses JSON responses.

        Args:
            response_text (str): The raw string generated by Gemini.
            default_val (Any): The fallback default value if parsing fails.

        Returns:
            Any: The parsed JSON object or default_val.
        """
        try:
            cleaned = response_text.strip()
            # Remove Markdown JSON block wrappers
            if cleaned.startswith("```json"):
                cleaned = cleaned[7:]
            elif cleaned.startswith("```"):
                cleaned = cleaned[3:]
            if cleaned.endswith("```"):
                cleaned = cleaned[:-3]
            cleaned = cleaned.strip()
            
            return json.loads(cleaned)
        except Exception as e:
            logger.warning(f"Failed to parse JSON response from Gemini: {e}. Raw response: {response_text}")
            return default_val

    def search_by_title(self, query: str) -> List[Dict[str, Any]]:
        """
        Searches posts by an exact or partial title match.

        Args:
            query (str): The search query text.

        Returns:
            List[Dict[str, Any]]: A list of matching posts.
        """
        default_fallback = [{"id": 1, "title": query or "Example Title", "match": "title"}]
        if not self.gemini_client:
            return default_fallback

        try:
            prompt = (
                f"Identify 3 calligraphy posts that contain or match the title query: '{query}'. "
                "Specify the post ID, title, and matching explanation. "
                "Respond ONLY with a JSON array of objects, where each object has these exact keys:\n"
                "  \"id\": [integer],\n"
                "  \"title\": \"Post Title\",\n"
                "  \"match\": \"title\",\n"
                "  \"reason\": \"Explanation of why the title matches the query\"\n"
            )
            full_prompt = f"{SYSTEM_INSTRUCTION}\n\nTask:\n{prompt}"
            response = self.gemini_client.generate_response(full_prompt)
            return self._parse_gemini_json(response, default_fallback)
        except Exception as e:
            logger.error(f"Error in search_by_title: {e}", exc_info=True)
            return default_fallback

    def search_by_style(self, style: str) -> List[Dict[str, Any]]:
        """
        Filters posts by a specific calligraphy style.

        Args:
            style (str): The calligraphy script style (e.g. Copperplate, Gothic).

        Returns:
            List[Dict[str, Any]]: A list of posts matching the style.
        """
        default_fallback = [{"id": 2, "style": style or "Cursive", "match": "style"}]
        if not self.gemini_client:
            return default_fallback

        try:
            prompt = (
                f"Identify 3 outstanding calligraphy posts created in the script style: '{style}'. "
                "Respond ONLY with a JSON array of objects, where each object has these exact keys:\n"
                "  \"id\": [integer],\n"
                "  \"style\": \"StatedStyleName\",\n"
                "  \"match\": \"style\",\n"
                "  \"reason\": \"Nuanced calligraphic description of the matching artwork\"\n"
            )
            full_prompt = f"{SYSTEM_INSTRUCTION}\n\nTask:\n{prompt}"
            response = self.gemini_client.generate_response(full_prompt)
            return self._parse_gemini_json(response, default_fallback)
        except Exception as e:
            logger.error(f"Error in search_by_style: {e}", exc_info=True)
            return default_fallback

    def search_by_language(self, language: str) -> List[Dict[str, Any]]:
        """
        Filters posts by the language of the calligraphy text.

        Args:
            language (str): The primary language of the text.

        Returns:
            List[Dict[str, Any]]: A list of matching posts.
        """
        default_fallback = [{"id": 3, "language": language or "English", "match": "language"}]
        if not self.gemini_client:
            return default_fallback

        try:
            prompt = (
                f"Identify 3 calligraphy posts written in the language: '{language}'. "
                "Respond ONLY with a JSON array of objects, where each object has these exact keys:\n"
                "  \"id\": [integer],\n"
                "  \"language\": \"StatedLanguage\",\n"
                "  \"match\": \"language\",\n"
                "  \"reason\": \"Context description of the script's textual contents\"\n"
            )
            full_prompt = f"{SYSTEM_INSTRUCTION}\n\nTask:\n{prompt}"
            response = self.gemini_client.generate_response(full_prompt)
            return self._parse_gemini_json(response, default_fallback)
        except Exception as e:
            logger.error(f"Error in search_by_language: {e}", exc_info=True)
            return default_fallback

    def search_by_tags(self, tags: Any) -> List[Dict[str, Any]]:
        """
        Searches posts that match a given set of tags.

        Args:
            tags: The tags criteria to match.

        Returns:
            List[Dict[str, Any]]: A list of matching posts.
        """
        tag_list = tags if isinstance(tags, list) else [str(tags)]
        default_fallback = [{"id": 4, "tags": tag_list, "match": "tags"}]
        if not self.gemini_client:
            return default_fallback

        try:
            prompt = (
                f"Identify 3 calligraphy posts matching the tags: '{tag_list}'. "
                "Respond ONLY with a JSON array of objects, where each object has these exact keys:\n"
                "  \"id\": [integer],\n"
                "  \"tags\": [\"array\", \"of\", \"matched\", \"tags\"],\n"
                "  \"match\": \"tags\",\n"
                "  \"reason\": \"Details of how these topics/tags describe the artwork\"\n"
            )
            full_prompt = f"{SYSTEM_INSTRUCTION}\n\nTask:\n{prompt}"
            response = self.gemini_client.generate_response(full_prompt)
            return self._parse_gemini_json(response, default_fallback)
        except Exception as e:
            logger.error(f"Error in search_by_tags: {e}", exc_info=True)
            return default_fallback

    def keyword_search(self, query: str) -> List[Dict[str, Any]]:
        """
        Performs a keyword-based search across titles, descriptions, and tags.

        Args:
            query (str): The keyword query.

        Returns:
            List[Dict[str, Any]]: A list of matching posts.
        """
        default_fallback = [{"id": 5, "description": "Beautiful artwork.", "match": "keyword"}]
        if not self.gemini_client:
            return default_fallback

        try:
            prompt = (
                f"Scan our platform context and generate 3 matching posts containing the keyword: '{query}'. "
                "Respond ONLY with a JSON array of objects, where each object has these exact keys:\n"
                "  \"id\": [integer],\n"
                "  \"description\": \"Title/Snippet of the matching post description containing keyword\",\n"
                "  \"match\": \"keyword\",\n"
                "  \"reason\": \"Highlight of where the keyword was matched\"\n"
            )
            full_prompt = f"{SYSTEM_INSTRUCTION}\n\nTask:\n{prompt}"
            response = self.gemini_client.generate_response(full_prompt)
            return self._parse_gemini_json(response, default_fallback)
        except Exception as e:
            logger.error(f"Error in keyword_search: {e}", exc_info=True)
            return default_fallback

    def semantic_search(self, query: str) -> List[Dict[str, Any]]:
        """
        Performs a semantic search to understand the intent and context of the query.

        Args:
            query (str): The natural language query.

        Returns:
            List[Dict[str, Any]]: A list of matching posts.
        """
        default_fallback = [{"id": 6, "context": "Deep contextual match.", "match": "semantic"}]
        if not self.gemini_client:
            return default_fallback

        try:
            prompt = (
                f"Evaluate the semantic meaning and calligraphic intent of the query: '{query}'. "
                "Find 3 highly contextually relevant matching posts on the platform. "
                "Respond ONLY with a JSON array of objects, where each object has these exact keys:\n"
                "  \"id\": [integer],\n"
                "  \"context\": \"Contextual topic matching query\",\n"
                "  \"match\": \"semantic\",\n"
                "  \"reason\": \"Explanation of why this matches the semantic intent of query\"\n"
            )
            full_prompt = f"{SYSTEM_INSTRUCTION}\n\nTask:\n{prompt}"
            response = self.gemini_client.generate_response(full_prompt)
            return self._parse_gemini_json(response, default_fallback)
        except Exception as e:
            logger.error(f"Error in semantic_search: {e}", exc_info=True)
            return default_fallback

    def search_posts(self, query: str = "", search_type: str = "keyword", filters: Dict[str, Any] = None) -> Dict[str, Any]:
        """
        Main orchestration method for the SearchAgent.
        
        Routes the search query to the appropriate specific search method based on search_type,
        and aggregates the resulting list of post matches.

        Args:
            query (str): Search input string.
            search_type (str): Search strategy (title, style, language, tags, semantic, keyword).
            filters (Dict[str, Any]): Supplementary filter parameters (e.g. style name, tags array).

        Returns:
            Dict[str, Any]: Structured search payload including results list, query, and count.
        """
        try:
            logger.info(f"Orchestrating search for query: '{query}' using type: {search_type}")
            results = []
            
            if filters is None:
                filters = {}

            # Route to the appropriate search strategy
            if search_type == "title":
                results = self.search_by_title(query)
            elif search_type == "style":
                results = self.search_by_style(filters.get("style", ""))
            elif search_type == "language":
                results = self.search_by_language(filters.get("language", ""))
            elif search_type == "tags":
                results = self.search_by_tags(filters.get("tags", []))
            elif search_type == "semantic":
                results = self.semantic_search(query)
            else:
                # Default to basic keyword search
                results = self.keyword_search(query)

            # Construct the final response dictionary
            response = {
                "query": query,
                "results": results,
                "count": len(results),
                "search_type": search_type
            }
            return response
            
        except Exception as e:
            logger.error(f"Error in search_posts orchestration: {e}", exc_info=True)
            # Return a graceful fallback dictionary
            return {
                "query": query,
                "results": [],
                "count": 0,
                "search_type": "error"
            }
